### PR TITLE
Update Demo Project to the latest fayde version.

### PR DESCRIPTION
**Pull request by Sally-Xu**

### CODE REVIEW

**Comment by BSick7** [comment]
Added typings hash to exjs library so that `ex.d.ts` is included in TodoApp build.

**Comment by BSick7** [comment]
Added back custom theming for NflDraft.

**Comment by Sally-Xu** [comment]
I found out the the map's problem is that Canvas can't seem to find any child in the constructor.

I added log in the Map constructor, the Children.Count returns 0.

class Map extends Fayde.Controls.Canvas {
    constructor() {  
        super();  
        var children = this.Children.getEnumerator();
        console.log(this.Children.Count);
 ..
}
}

**Comment by Sally-Xu** [comment]
Todo App is fixed after adding /// <reference path="../lib/exjs/dist/ex.d.ts" /> in the MainViewModel.ts. 
It can be built without any error. 

But somehow Visual Studio still put a red line under i.IsComplete in the following code for some reason.

return ex(this.Items).count(i => i.IsComplete);

**Comment by BSick7** [comment]
Visual Studio is probably having trouble resolving the result of ex(...) which needs the `ex.d.ts` file.

**Pull request merged**
